import {
  PersonRole,
  ScheduleCAccountingMethod,
  ScheduleCData,
  ScheduleFData
} from 'ustaxes/core/data'

export const business: ScheduleCData = {
  businessName: 'Synthetic business',
  businessCode: '541990',
  accountingMethod: ScheduleCAccountingMethod.Cash,
  didMateriallyParticipate: true,
  didStartBusiness: false,
  didMakePaymentsRequiring1099: false,
  didFile1099s: false,
  personRole: PersonRole.PRIMARY,
  grossReceipts: 10000,
  returns: 0,
  costOfGoodsSold: 0,
  otherIncome: 0,
  advertising: 0,
  carAndTruck: 0,
  commissions: 0,
  contractLabor: 0,
  depletion: 0,
  depreciation: 0,
  employeeBenefits: 0,
  insurance: 0,
  interestMortgage: 0,
  interestOther: 0,
  legal: 0,
  officeExpense: 0,
  pensionProfitSharing: 0,
  rentVehicles: 0,
  rentOther: 0,
  repairs: 0,
  supplies: 2000,
  taxes: 0,
  travel: 0,
  meals: 0,
  utilities: 0,
  wages: 0,
  otherExpenses: 0
}

export const farm: ScheduleFData = {
  farmName: 'Synthetic farm',
  accountingMethod: 'Cash',
  personRole: PersonRole.PRIMARY,
  salesLivestock: 10000,
  costLivestock: 0,
  cooperativeDistributions: 0,
  agriculturePayments: 0,
  cccLoans: 0,
  cropInsurance: 0,
  customHireIncome: 0,
  otherFarmIncome: 0,
  carAndTruck: 0,
  chemicals: 0,
  conservation: 0,
  customHire: 0,
  depreciation: 0,
  employeeBenefits: 0,
  feed: 2000,
  fertilizers: 0,
  freight: 0,
  fuel: 0,
  insurance: 0,
  interestMortgage: 0,
  interestOther: 0,
  labor: 0,
  pensionProfitSharing: 0,
  rentVehicles: 0,
  rentOther: 0,
  repairs: 0,
  seeds: 0,
  storage: 0,
  supplies: 0,
  taxes: 0,
  utilities: 0,
  veterinary: 0,
  otherExpenses: 0
}
